#!/bin/bash

# Use local X server - allow local X connection from the docker instance
if [[ -z "$(xhost|grep LOCAL)" ]]; then
	xhost +local:
fi

# $* to pass on any options from the command line
docker run --name eclipse --rm -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:ro -v eclipse:/home/developer/ --net=host $* cxai/cxeclipse