#!/bin/bash

cid=cxai/cxintellij
# Use local X server - allow local X connection from the docker instance
if [[ -z "$(xhost|grep LOCAL)" ]]; then
	xhost +local:$(docker inspect --format='{{ .Config.Hostname }}' $cid)
fi

# $* to pass on any options from the command line
docker run --name intellij --rm -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:ro -v intellij:/root/ $cid $*
